GET https://{{$dotenv STORAGE_ACCOUNT_NAME}}.blob.core.windows.net/{{$dotenv CONTAINER_NAME}}?restype=container&comp=list
x-ms-version: {{$dotenv X-MS-VERSION}}
Authorization: Bearer {{$dotenv BEARER_STORAGE}}